name: ci

on:
  pull_request:

jobs:
  docker:
    runs-on: 	ubuntu-24.04-arm
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: false
          tags: user/app:latest
